Name: Huawei Han 
Github Username: HuaweiH
USC ID: 8850211586

In [1]:
import pandas as pd
import numpy as np

## Question 4

In [2]:
salaries_data = pd.read_csv('Salaries.csv', index_col='playerID', header=0, skiprows=[1])
salaries_data

yearID teamID lgID    salary
playerID                               
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
chambch01    1985    ATL   NL    800000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25574 rows x 4 columns]

In [3]:
salaries_data[(salaries_data['teamID']=="ATL") & (salaries_data['salary']>1000000) | 
              (salaries_data['teamID']=="HOU") & (salaries_data['salary']>1000000)].index

Index(['hornebo01', 'murphda05', 'suttebr01', 'ryanno01', 'hornebo01',
       'murphda05', 'suttebr01', 'ryanno01', 'griffke01', 'murphda05',
       ...
       'feldmsc01', 'gonzama01', 'gregelu01', 'lowrije01', 'neshepa01',
       'quallch01', 'rasmuco01', 'singljo02', 'sippto01', 'valbulu01'],
      dtype='object', name='playerID', length=595)

In [4]:
salaries_data[(salaries_data['teamID']=="ATL")].salary.describe()

count    8.850000e+02
mean     2.207749e+06
std      3.434320e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.400000e+06
max      1.606180e+07
Name: salary, dtype: float64

In [5]:
sala_dict = {"playerID":[], "yearID":[], "teamID":[], "lgID":[], "salary":[]}
for row in salaries_data.iterrows():
    sala_dict['playerID'].append(row[0])
    sala_dict['yearID'].append(row[1].yearID)
    sala_dict['teamID'].append(row[1].teamID)
    sala_dict['lgID'].append(row[1].lgID)
    sala_dict['salary'].append(row[1].salary)


In [6]:
df = pd.DataFrame(data=sala_dict)
new_col = {'playerID':'a', 'yearID':'b', 'teamID':'c', 'lgID':'d', 'salary':'e'}
df.rename(columns=new_col, inplace=True)
df

a     b    c   d         e
0      bedrost01  1985  ATL  NL    550000
1      benedbr01  1985  ATL  NL    545000
2       campri01  1985  ATL  NL    633333
3      ceronri01  1985  ATL  NL    625000
4      chambch01  1985  ATL  NL    800000
...          ...   ...  ...  ..       ...
25569  treinbl01  2015  WAS  NL    512800
25570  ugglada01  2015  WAS  NL    507500
25571  werthja01  2015  WAS  NL  21000000
25572  zimmejo02  2015  WAS  NL  16500000
25573  zimmery01  2015  WAS  NL  14000000

[25574 rows x 5 columns]

## Question 5

In [7]:
ls = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(ls)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
print('ndim: ', arr.ndim) 
print('shape: ', arr.shape) 
print('size: ', arr.size) 
print('itemsize: ', arr.itemsize) 
print('data: ', arr.data) 

ndim:  2
shape:  (4, 3)
size:  12
itemsize:  8
data:  <memory at 0x7f9e78503110>


In [33]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.linspace(0,7,11)

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3, 7. ])

In [39]:
np.concatenate((np.arange(9),np.ones(3)), axis=None)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 1., 1., 1.])

In [41]:
$ git init

SyntaxError: invalid syntax (852734176.py, line 1)